### ISSUE TITLE
Lazy Load example

### ISSUE THREAD

**Issue by dfliess** [redpie/backbone-schema#1]
On the README.MD when gives the Lazy Load example I think it should be:

// Create person but don't provide any attribute data yet
var person = new PersonModel();

// the address attribute starts off undefined
var hasAddressModel = person.attributes['address'] === undefined; **// true**
// returns a new AddressSchemaModel
**people**.get('address');
// You can now see the address attribute is initialized
hasAddressModel = person.attributes['address'] === undefined; **// false**

also with the collection example.

I think it would be great to specify when to use lazy Loading or Deep Fetch level maybe ? The most common use case I think would be Deep Fetch simple object/Models and Lazy Load Collections for example....

**Comment by marcusmacinnes** [comment]
On the README.MD docs, you are quite right. Thanks. If you'd like to create a PR I'll merge, otherwise I'll update the docs shortly.

Can you explain Lazy / Deep Fetch issue a bit more? We don't provide any sync logic so loading is currently up to you. 

We provide "lazy initialization" (as opposed to lazy loading) meaning that when you initialize a model, empty child models and collections are not created until they are required. This is done for performance reasons and avoids creating unnecessary models and collections which may be defined in schema but not required for a given instance.

**Comment by dfliess** [comment]
Hi marcus, sorry for the delay, I went out for the weekend :smile: 
good you updated docs.
About the Lazy Loading, maybe I expressed my self wrong and confused you with the Fetch term (I do not know how to call it in this case in english to the oposito for lazy loading), but the idea is to specify up to which level you want your models to be created/loaded, so that for simple objects (like the address) you don't need to get it and then prompt for it. it's better explained now ?

**Comment by marcusmacinnes** [comment]
@dfliess The design of the lazy initialization minimizes the number of objects that are created for performance reasons and minimizing memory consumption. Although the docs show a model.get('attribute'), this was only to show that the object itself wasn't created until it was accessed.

You don't need to get a model before you can set it. You can simple set an uninitialized model attribute directly like:

``` javascript
var person = new PersonModel({
     "name": "Marcus"
});

// At this point the address attribute is undefined
person.set('address', {
    "addressline1": "19 Greek Street",
    "addressline2": "Soho",
    "city": "London",
    "country": "UK"
});
// Now the address attribute is an instance of AddressModel 
```

Under the covers we override Backbone.Model.get and Backbone.Model.set and catch any attempt to get or set attributes whose schema is defined as an object or a collection and initialize the instance only when required.

What we do not currently do, is lazy build the model and collection types. When you create a type using Backbone.Schema.Factory's create method, the model or collection type is created along with corresponding types for all possible children (recursively) which depending on the complexity of your schema could be a large number. It's best practice to create your models or collections as you need them rather than doing it up front. Previously created types are cached where possible to avoid building duplicates.

Does this help?

**Comment by dfliess** [comment]
yes. thanks!
